# Generated by Django 5.0.4 on 2024-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangjobs',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
